apiVersion : apps/v1
kind: Deployment
metadata:
  name: whoami 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: whoami 
    spec:
      containers:
        - name: whoami 
          image: shipu.azurecr.io/whoami
          ports:
          - containerPort: 80
