apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: whoami
  name: whoami
  namespace: default
spec:
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - image: shipu.azurecr.io/whoami
        imagePullPolicy: Always
        name: whoami
        ports:
         - containerPort: 80
